# Generated by Django 5.0.3 on 2024-03-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('publishing_datetime', models.DateTimeField()),
                ('video_id', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
