# Generated by Django 5.0.3 on 2024-03-13 16:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_name', models.CharField(max_length=50)),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('uploads_playlist_id', models.CharField(max_length=50)),
                ('channel_description', models.TextField()),
                ('subscriber_count', models.BigIntegerField()),
                ('view_count', models.BigIntegerField()),
                ('video_count', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ChannelList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50, unique=True)),
                ('start_date', models.DateTimeField(default=datetime.datetime.now, null=True)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=5000)),
                ('description', models.TextField()),
                ('tags', models.CharField(max_length=500)),
                ('deleted', models.BooleanField(default=False)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.channel')),
            ],
        ),
        migrations.CreateModel(
            name='VideoStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_count', models.BigIntegerField()),
                ('like_count', models.BigIntegerField()),
                ('favorite_count', models.BigIntegerField()),
                ('comment_count', models.BigIntegerField()),
                ('timestamp', models.DateTimeField()),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.video')),
            ],
        ),
        migrations.DeleteModel(
            name='YouTubeVideo',
        ),
    ]
